### ISSUE TITLE
weft_derive needs updating on crates.io?

### ISSUE THREAD

**Issue by mikebelanger** [cstorey/weft#80]
Project is really cool!  I'm glad I'm not the only one who thinks we can template HTML with attributes.

I was trying to use this with a new project using the 2021 edition, but I'm running into build problems.

Rust version: 
```
stable-x86_64-unknown-linux-gnu unchanged - rustc 1.73.0 (cc66ad468 2023-10-03)
```
Cargo.toml:
```
[package]
name = "weft_problem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
weft = "0.1.0"
weft_derive = "0.1.1"
```

main.rs:
```
use weft_derive::WeftRenderable;

#[derive(WeftRenderable)]
#[template(path = "src/interpolatable.html")]
struct Interpolatable<'a> {
    name: &'a str,
}

fn main() {
    println!("Hello, world!");
}
```

Output:
```
[mike@mike-um350 weft_problem]$ cargo build
   Compiling weft_problem v0.1.0 (/home/mike/Projects/weft/weft_problem)
error[E0432]: unresolved import `weft`
 --> src/main.rs:3:10
  |
3 | #[derive(WeftRenderable)]
  |          ^^^^^^^^^^^^^^ could not find `prelude` in `weft`
  |
  = note: this error originates in the derive macro `WeftRenderable` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0432`.
error: could not compile `weft_problem` (bin "weft_problem") due to previous error
```

Upon inspecting the source in `lib.rs` in this repo and comparing it to that corresponding file on my machine, it looks like mine is an older version.  If I download this repo and run each thing, the build works successfully.

Anyways, I think this is a cool project so I'd hate to think its getting skipped over because of a minor update hiccup.

**Comment by cstorey** [comment]
Hi,

It's cool to hear someone is using this :) Unfortunately, i've not really had the time or energy to maintain it properly over the past few years, so feel free to play with it, but I'd not want to rely on it for production use.

I've pubished 0.1.2 to crates.io though.
